theme: minima
title: More Filters Pls
author: MoreFiltersPls
#email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Augmented Reality Projects for you!

# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  MoreFiltersPls # DO NOT include the @ character, or else the build will fail!
instagram_username: MoreFiltersPls

show_excerpts: true # set to false to remove excerpts on the homepage
